<a href="https://colab.research.google.com/github/Harleen2608/Harleen2608/blob/main/Numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
NumPy is a Python library.

NumPy is used for working with arrays.

NumPy is short for "Numerical Python".

In [ ]:
#creaing an array
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,0])
print(arr)
print(type(arr))


[1 2 3 4 5 6 7 8 9 0]
<class 'numpy.ndarray'>


In [ ]:
#ckecking for version
print(np.__version__)

1.25.2


In [ ]:
Dimension in array

In [ ]:
# 0-d array
zero=np.array(26)
zero

array(26)

In [ ]:
#1-d array
one=np.array([1,2,3,4])
one

array([1, 2, 3, 4])

In [ ]:
#2-d array
two=np.array([[1,2,7],[3,4,5]])
two


array([[1, 2, 7],
       [3, 4, 5]])

In [ ]:
#3-d array
three=np.array([[[1,2,3],[2,3,4]],[[3,6,7],[7,8,9]]])
three

array([[[1, 2, 3],
        [2, 3, 4]],

       [[3, 6, 7],
        [7, 8, 9]]])

In [ ]:
#CKECKING FOR DIMENSION OF ARRYS

In [ ]:
print(one.ndim)
print(zero.ndim)
print(three.ndim)
print(two.ndim)


1
0
3
2


In [ ]:
#HIGHLY ORDER DIMENSION USING  ndmin ARGUMENT

In [ ]:
arr=np.array([1,2],ndmin=6)
arr

array([[[[[[1, 2]]]]]])

In [ ]:
#ARRAY ACCESSING VIA INDEXING

In [ ]:
print(one[3])

4


In [ ]:
print(two[1,2])

5


In [ ]:
print(three[1,0,1])

6


In [ ]:
print(one[-1])

4


In [ ]:
print(two[-2,-1])

7


In [ ]:
print(three[-1,0,-1])

7


In [ ]:
one[1:2]